import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { TiMessages } from "react-icons/ti";
import Header from "../components/Header";
import Homes from "../components/Home";

export default function Home() {
  const [click, setClick] = useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main__container w-100 min-h-full bg-gray-600">
        <Header />
        <Homes />
        <h1>Salom</h1>
      </div>
    </div>
  );
}
